### ISSUE TITLE
plugin load fail

### ISSUE THREAD

**Issue by ron0115** [theme-next/hexo-next-utteranc#5]
![image](https://user-images.githubusercontent.com/20643950/72233907-0253bc80-3605-11ea-8c20-178674d13e0d.png)

__config.yml
```
# Utteranc
# Demo: https://utteranc.es/
# For more information: http://trumandu.github.io/about/
utteranc:
  enable: true
  repo: ron0015/ron0015.github.io
  # theme: github-light,github-dark,github-dark-orange
  theme: github-light
  cdn: https://utteranc.es/client.js
```
package.json
```
{
    "hexo-next-utteranc": "github:theme-next/hexo-next-utteranc"
}
```

以上是我的配置，在`hexo server`和`hexo generate`的时候都有问题
